function(add_platform_definitions)
  if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(BUILD_WINDOWS TRUE PARENT_SCOPE)
    add_definitions(-DBUILD_WINDOWS)
  elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(BUILD_LINUX TRUE PARENT_SCOPE)
    add_definitions(-DBUILD_LINUX)
    add_definitions(-DBUILD_OSX)
  elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(BUILD_OSX TRUE PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Unsupported OS ${CMAKE_SYSTEM_NAME}")
  endif()
endfunction()

